# Generated by Django 3.1.2 on 2020-10-08 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordpair',
            old_name='tarnslation',
            new_name='translation',
        ),
    ]
